name: Black Lint

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          # TODO(klecki): Deduplicate this list of directories with `lint.cmake` file
          src: "./dali ./docs ./tools ./dali_tf_plugin ./qa ./dali/python/nvidia/dali/_autograph ./dali/test/python/autograph/"
          jupyter: true
          version: "23.11.0"
